### PR TITLE
Fix #2740, write i18n.csv on demand

### LINKED ISSUE #2740: 4.1.9.1 doesn't start
### Shadowsocks version / 影梭版本
4.1.9.1

### Environment (Operating system, .NET Framework, etc) / 使用环境（操作系统，.NET Framework等）
Win 10 x64 1909, .NET Framework 1.1, 2.0.50727, 3.0, 3.5, 4.0, 4.8

### Steps you have tried / 操作步骤
just replaced .exe with new version 

### What did you expect to see? / 期望的结果
Icon in tray

### What did you see instead? / 实际结果
Nothing

### Config and error log in detail (with all sensitive info masked) / 配置文件和日志文件（请隐去敏感信息）
```
[2019-12-22 13:13:29] Current language is: ru-RU
[2019-12-22 13:13:29] [E] System.TypeInitializationException: Инициализатор типа "Shadowsocks.Controller.I18N" выдал исключение. ---> System.IndexOutOfRangeException: Индекс находился вне границ массива.
   в Shadowsocks.Controller.I18N.Init(String res, String locale)
   в Shadowsocks.Controller.I18N..cctor()
   --- Конец трассировки внутреннего стека исключений ---
   в Shadowsocks.Controller.I18N.GetString(String key, Object[] args)
   в Shadowsocks.View.MenuViewController.CreateMenuItem(String text, EventHandler click)
   в Shadowsocks.View.MenuViewController.LoadMenu()
   в Shadowsocks.View.MenuViewController..ctor(ShadowsocksController controller)
   в Shadowsocks.Program.Main(String[] args)
```

```
{
  "version": "4.1.8.0",
  "configs": [
    {
      "server": "xxx",
      "server_port": 8488,
      "password": "xxx",
      "method": "aes-256-gcm",
      "plugin": "",
      "plugin_opts": "",
      "plugin_args": "",
      "remarks": "xxx",
      "timeout": 5
    }
  ],
  "strategy": null,
  "index": 0,
  "global": false,
  "enabled": false,
  "shareOverLan": false,
  "isDefault": false,
  "isIPv6Enabled": false,
  "localPort": 1088,
  "portableMode": true,
  "pacUrl": null,
  "useOnlinePac": false,
  "secureLocalPac": true,
  "availabilityStatistics": false,
  "autoCheckUpdate": false,
  "checkPreRelease": false,
  "isVerboseLogging": false,
  "logViewer": {
    "topMost": false,
    "wrapText": false,
    "toolbarShown": false,
    "Font": "Cuprum, 11.25pt",
    "BackgroundColor": "Black",
    "TextColor": "White"
  },
  "proxy": {
    "useProxy": false,
    "proxyType": 0,
    "proxyServer": "",
    "proxyPort": 0,
    "proxyTimeout": 3,
    "useAuth": false,
    "authUser": "",
    "authPwd": ""
  },
  "hotkey": {
    "SwitchSystemProxy": "",
    "SwitchSystemProxyMode": "",
    "SwitchAllowLan": "",
    "ShowLogs": "",
    "ServerMoveUp": "",
    "ServerMoveDown": "",
    "RegHotkeysAtStartup": false
  }
}
```

### PR DESCRIPTION
**Pull request by studentmain**
## Please follow the guide below

- You will be asked some questions, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *pull request* (like that [x])
- Use *Preview* tab to see how your *pull request* will actually look like

- [x] [Searched](https://github.com/shadowsocks/shadowsocks-windows/search?q=is%3Apr&type=Issues) for similar pull requests
- [ ] Compiled the code with Visual Studio
- [ ] Require translation update
- [x] Require document update (readme.md, wikipage, etc)

### What is the purpose of your *pull request*?
- [x] Bug fix
- [x] Improvement
- [ ] New feature

---

### Description of your *pull request* and other information

Explanation of your *pull request* in arbitrary form goes here. Please make sure the description explains the purpose and effect of your *pull request* and is worded well enough to be understood. Provide as much context and examples as possible.

### CODE REVIEW

File: shadowsocks-csharp/View/MenuViewController.cs [hunk 1]
```diff
@@ -322,6 +320,7 @@ private void LoadMenu()
                     CreateMenuItem("Show Logs...", new EventHandler(this.ShowLogItem_Click)),
                     this.VerboseLoggingToggleItem = CreateMenuItem( "Verbose Logging", new EventHandler(this.VerboseLoggingToggleItem_Click) ),
                     this.ShowPluginOutputToggleItem = CreateMenuItem("Show Plugin Output", new EventHandler(this.ShowPluginOutputToggleItem_Click)),
+                    this.WriteI18NFileItem = CreateMenuItem("Write translation template",new EventHandler(WriteI18NFileItem_Click)),
```
Comment (celeron533) [inline shadowsocks-csharp/View/MenuViewController.cs]: Why need this menu? What will happen if user generated an old csv file then user upgrade SS to a new version with new UI elements?

Comment (studentmain) [reply shadowsocks-csharp/View/MenuViewController.cs]: > Why need this menu?

user can translate the program by edit generated csv

> What will happen

New translation won't apply

Comment (celeron533) [reply shadowsocks-csharp/View/MenuViewController.cs]: > New translation won't apply

IMO, if users need a new language or amend the translation, let them send pull request. Otherwise, by use of an external translation file may cause some "out-of-date" problem after upgrade.

Comment (celeron533) [reply shadowsocks-csharp/View/MenuViewController.cs]: If you feel it doesn't matter, please merge the PR.

Comment (studentmain) [reply shadowsocks-csharp/View/MenuViewController.cs]: @chenshaoju How do you think?

Comment (chenshaoju) [reply shadowsocks-csharp/View/MenuViewController.cs]: My programming is bad...
Looks good, build succeeded, I think is good.

Comment (studentmain) [reply shadowsocks-csharp/View/MenuViewController.cs]: > "out-of-date" problem 

will implement translate file merge to resolve this

Comment (celeron533) [reply shadowsocks-csharp/View/MenuViewController.cs]: > will implement translate file merge to resolve this

What will happen if there is a conflict or obsoleted item in new version? This is what I am worrying about. Too much user interactions.
Or your design purpose is to switch between "integrated translation resource" and "external translation file" in the future?

Comment (studentmain) [reply shadowsocks-csharp/View/MenuViewController.cs]: > conflict

use external one, as user may changed it

> obsoleted

just keep it, user can downgrade version

Comment (celeron533) [reply shadowsocks-csharp/View/MenuViewController.cs]: OK I will draft a new release soon
